# Generated by Django 5.2.15 on 2026-07-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='fastestgrowingmarket',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fastestgrowingmarket',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='marketmetric',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='marketmetric',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='neighborhoodintel',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='neighborhoodintel',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
