# Generated by Django 5.2.15 on 2026-06-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('headline', models.CharField(max_length=500)),
                ('subheadline', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(choices=[('NOTABLE_SALE', 'Notable Sale'), ('AGENT_WATCH', 'Agent Watch'), ('NEIGHBORHOOD_WATCH', 'Neighborhood Watch'), ('DEVELOPMENT', 'Development'), ('MARKET_PULSE', 'Market Pulse')], max_length=30)),
                ('body', models.TextField()),
                ('byline', models.CharField(max_length=255)),
                ('author_avatar_url', models.URLField(blank=True)),
                ('read_time_minutes', models.PositiveSmallIntegerField(default=3)),
                ('hero_image_url', models.URLField(blank=True)),
                ('published_date', models.DateField()),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
