# Generated by Django 5.2.15 on 2026-06-25 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotableSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('SOUTH_FLORIDA', 'South Florida'), ('TAMPA_BAY', 'Tampa Bay'), ('ORLANDO', 'Orlando'), ('JACKSONVILLE', 'Jacksonville'), ('PANHANDLE', 'Panhandle')], max_length=20)),
                ('property_type', models.CharField(choices=[('WATERFRONT_ESTATE', 'Waterfront Estate'), ('CONDO_PENTHOUSE', 'Condo Penthouse'), ('CONDO_RESIDENCE', 'Condo Residence'), ('COMMERCIAL', 'Commercial'), ('SINGLE_FAMILY', 'Single Family')], max_length=20)),
                ('close_date', models.DateField()),
                ('hero_image_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('brokerage', models.CharField(blank=True, max_length=255)),
                ('beds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('baths', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('sq_ft', models.PositiveIntegerField(blank=True, null=True)),
                ('article', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='articles.article')),
            ],
            options={
                'ordering': ['-close_date', '-price'],
            },
        ),
    ]
