# Generated by Django 5.2.15 on 2026-07-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notablesale',
            name='source_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notablesale',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='notablesale',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('PUBLISHED', 'Published')], default='PUBLISHED', max_length=20),
        ),
    ]
